// <auto-generated />
namespace topface.Migrations
{
    using System.CodeDom.Compiler;
    using System.Data.Entity.Migrations;
    using System.Data.Entity.Migrations.Infrastructure;
    using System.Resources;
    
    [GeneratedCode("EntityFramework.Migrations", "6.1.3-40302")]
    public sealed partial class changetolong : IMigrationMetadata
    {
        private readonly ResourceManager Resources = new ResourceManager(typeof(changetolong));
        
        string IMigrationMetadata.Id
        {
            get { return "201807092043127_change-to-long"; }
        }
        
        string IMigrationMetadata.Source
        {
            get { return null; }
        }
        
        string IMigrationMetadata.Target
        {
            get { return Resources.GetString("Target"); }
        }
    }
}
